//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.20 at 08:50:26 下午 CST 
//


package com.bwzk.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Table" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DEP_ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="DEP_PARENT_ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="DEP_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DEP_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DEP_ORDER" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="DEP_TYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="DEP_ATTRIBUTES" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DEP_PLATFORMID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "table"
})
@XmlRootElement(name = "NewDataSet")
public class MLDepNewDataSet {

    @XmlElement(name = "Table")
    protected List<MLDepNewDataSet.Table> table;

    /**
     * Gets the value of the table property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the table property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MLDepNewDataSet.Table }
     * 
     * 
     */
    public List<MLDepNewDataSet.Table> getTable() {
        if (table == null) {
            table = new ArrayList<MLDepNewDataSet.Table>();
        }
        return this.table;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DEP_ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="DEP_PARENT_ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="DEP_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DEP_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DEP_ORDER" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="DEP_TYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="DEP_ATTRIBUTES" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DEP_PLATFORMID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "depid",
        "depparentid",
        "depcode",
        "depname",
        "deporder",
        "deptype",
        "depattributes",
        "depplatformid"
    })
    public static class Table {

        @XmlElement(name = "DEP_ID")
        protected Integer depid;
        @XmlElement(name = "DEP_PARENT_ID")
        protected Integer depparentid;
        @XmlElement(name = "DEP_CODE", required = true)
        protected String depcode;
        @XmlElement(name = "DEP_NAME", required = true)
        protected String depname;
        @XmlElement(name = "DEP_ORDER")
        protected Integer deporder;
        @XmlElement(name = "DEP_TYPE")
        protected Integer deptype;
        @XmlElement(name = "DEP_ATTRIBUTES", required = true)
        protected String depattributes;
        @XmlElement(name = "DEP_PLATFORMID")
        protected Integer depplatformid;

		/**
         * Gets the value of the depid property.
         * 
         */
        public Integer getDEPID() {
            return depid;
        }

        /**
         * Sets the value of the depid property.
         * 
         */
        public void setDEPID(Integer value) {
            this.depid = value;
        }

        /**
         * Gets the value of the depparentid property.
         * 
         */
        public Integer getDEPPARENTID() {
            return depparentid;
        }

        /**
         * Sets the value of the depparentid property.
         * 
         */
        public void setDEPPARENTID(Integer value) {
            this.depparentid = value;
        }

        /**
         * Gets the value of the depcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDEPCODE() {
            return depcode;
        }

        /**
         * Sets the value of the depcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDEPCODE(String value) {
            this.depcode = value;
        }

        /**
         * Gets the value of the depname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDEPNAME() {
            return depname;
        }

        /**
         * Sets the value of the depname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDEPNAME(String value) {
            this.depname = value;
        }

        /**
         * Gets the value of the deporder property.
         * 
         */
        public Integer getDEPORDER() {
            return deporder;
        }

        /**
         * Sets the value of the deporder property.
         * 
         */
        public void setDEPORDER(Integer value) {
            this.deporder = value;
        }

        /**
         * Gets the value of the deptype property.
         * 
         */
        public Integer getDEPTYPE() {
            return deptype;
        }

        /**
         * Sets the value of the deptype property.
         * 
         */
        public void setDEPTYPE(Integer value) {
            this.deptype = value;
        }

        /**
         * Gets the value of the depattributes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDEPATTRIBUTES() {
            return depattributes;
        }

        /**
         * Sets the value of the depattributes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDEPATTRIBUTES(String value) {
            this.depattributes = value;
        }

        /**
         * Gets the value of the depplatformid property.
         * 
         */
        public Integer getDEPPLATFORMID() {
            return depplatformid;
        }

        /**
         * Sets the value of the depplatformid property.
         * 
         */
        public void setDEPPLATFORMID(Integer value) {
            this.depplatformid = value;
        }

    }

}
