//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.20 at 08:50:26 下午 CST 
//


package com.bwzk.pojo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bwzk.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class MLDepObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bwzk.pojo
     * 
     */
    public MLDepObjectFactory() {
    }

    /**
     * Create an instance of {@link MLDepNewDataSet }
     * 
     */
    public MLDepNewDataSet createNewDataSet() {
        return new MLDepNewDataSet();
    }

    /**
     * Create an instance of {@link MLDepNewDataSet.Table }
     * 
     */
    public MLDepNewDataSet.Table createNewDataSetTable() {
        return new MLDepNewDataSet.Table();
    }

}
