//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.02 at 05:37:31 下午 CST 
//


package com.bwzk.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Task" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="F_TaskID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="F_NetModuleID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="F_TaskName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="F_BeginDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="F_CreateDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="F_CreatorUsrName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="F_TaskLinkUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "task"
})
@XmlRootElement(name = "ToDoTasks")
public class MlToDoTask {

    @XmlElement(name = "Task")
    protected List<MlToDoTask.Task> task;

    /**
     * Gets the value of the task property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the task property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTask().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MlToDoTask.Task }
     * 
     * 
     */
    public List<MlToDoTask.Task> getTask() {
        if (task == null) {
            task = new ArrayList<MlToDoTask.Task>();
        }
        return this.task;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="F_TaskID" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="F_NetModuleID" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="F_TaskName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="F_BeginDate" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="F_CreateDate" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="F_CreatorUsrName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="F_TaskLinkUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Task {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "F_TaskID")
        protected Integer fTaskID;
        @XmlAttribute(name = "F_NetModuleID")
        protected Integer fNetModuleID;
        @XmlAttribute(name = "F_TaskName")
        protected String fTaskName;
        @XmlAttribute(name = "F_BeginDate")
        protected String fBeginDate;
        @XmlAttribute(name = "F_CreateDate")
        protected String fCreateDate;
        @XmlAttribute(name = "F_CreatorUsrName")
        protected String fCreatorUsrName;
        @XmlAttribute(name = "F_TaskLinkUrl")
        protected String fTaskLinkUrl;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the fTaskID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFTaskID() {
            return fTaskID;
        }

        /**
         * Sets the value of the fTaskID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFTaskID(Integer value) {
            this.fTaskID = value;
        }

        /**
         * Gets the value of the fNetModuleID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFNetModuleID() {
            return fNetModuleID;
        }

        /**
         * Sets the value of the fNetModuleID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFNetModuleID(Integer value) {
            this.fNetModuleID = value;
        }

        /**
         * Gets the value of the fTaskName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFTaskName() {
            return fTaskName;
        }

        /**
         * Sets the value of the fTaskName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFTaskName(String value) {
            this.fTaskName = value;
        }

        /**
         * Gets the value of the fBeginDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFBeginDate() {
            return fBeginDate;
        }

        /**
         * Sets the value of the fBeginDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFBeginDate(String value) {
            this.fBeginDate = value;
        }

        /**
         * Gets the value of the fCreateDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFCreateDate() {
            return fCreateDate;
        }

        /**
         * Sets the value of the fCreateDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFCreateDate(String value) {
            this.fCreateDate = value;
        }

        /**
         * Gets the value of the fCreatorUsrName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFCreatorUsrName() {
            return fCreatorUsrName;
        }

        /**
         * Sets the value of the fCreatorUsrName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFCreatorUsrName(String value) {
            this.fCreatorUsrName = value;
        }

        /**
         * Gets the value of the fTaskLinkUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFTaskLinkUrl() {
            return fTaskLinkUrl;
        }

        /**
         * Sets the value of the fTaskLinkUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFTaskLinkUrl(String value) {
            this.fTaskLinkUrl = value;
        }

    }

}
