//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.20 at 08:51:13 下午 CST 
//


package com.bwzk.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Table" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="USR_ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="USR_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="USR_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="USR_DEP_ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="USR_ORDER" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="USR_SEX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="USR_MOBILE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="USR_OFFICE_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="USR_STATUS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="USR_PWDMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="USR_PLATFORMID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "table"
})
@XmlRootElement(name = "NewDataSet")
public class MLUsrDataSet {

    @XmlElement(name = "Table")
    protected List<MLUsrDataSet.Table> table;

    /**
     * Gets the value of the table property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the table property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MLUsrDataSet.Table }
     * 
     * 
     */
    public List<MLUsrDataSet.Table> getTable() {
        if (table == null) {
            table = new ArrayList<MLUsrDataSet.Table>();
        }
        return this.table;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="USR_ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="USR_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="USR_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="USR_DEP_ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="USR_ORDER" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="USR_SEX" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="USR_MOBILE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="USR_OFFICE_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="USR_STATUS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="USR_PWDMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="USR_PLATFORMID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "usrid",
        "usrcode",
        "usrname",
        "usrdepid",
        "usrorder",
        "usrsex",
        "usrmobile",
        "usrofficeemail",
        "usrstatus",
        "usrpwdmd5",
        "usrplatformid"
    })
    public static class Table {

        @XmlElement(name = "USR_ID")
        protected Integer usrid;
        @XmlElement(name = "USR_CODE", required = true)
        protected String usrcode;
        @XmlElement(name = "USR_NAME", required = true)
        protected String usrname;
        @XmlElement(name = "USR_DEP_ID")
        protected Integer usrdepid;
        @XmlElement(name = "USR_ORDER")
        protected Integer usrorder;
        @XmlElement(name = "USR_SEX", required = true)
        protected String usrsex;
        @XmlElement(name = "USR_MOBILE", required = true)
        protected String usrmobile;
        @XmlElement(name = "USR_OFFICE_EMAIL", required = true)
        protected String usrofficeemail;
        @XmlElement(name = "USR_STATUS")
        protected Integer usrstatus;
        @XmlElement(name = "USR_PWDMD5", required = true)
        protected String usrpwdmd5;
        @XmlElement(name = "USR_PLATFORMID")
        protected Integer usrplatformid;

        /**
         * Gets the value of the usrid property.
         * 
         */
        public Integer getUSRID() {
            return usrid;
        }

        /**
         * Sets the value of the usrid property.
         * 
         */
        public void setUSRID(Integer value) {
            this.usrid = value;
        }

        /**
         * Gets the value of the usrcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSRCODE() {
            return usrcode;
        }

        /**
         * Sets the value of the usrcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSRCODE(String value) {
            this.usrcode = value;
        }

        /**
         * Gets the value of the usrname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSRNAME() {
            return usrname;
        }

        /**
         * Sets the value of the usrname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSRNAME(String value) {
            this.usrname = value;
        }

        /**
         * Gets the value of the usrdepid property.
         * 
         */
        public Integer getUSRDEPID() {
            return usrdepid;
        }

        /**
         * Sets the value of the usrdepid property.
         * 
         */
        public void setUSRDEPID(Integer value) {
            this.usrdepid = value;
        }

        /**
         * Gets the value of the usrorder property.
         * 
         */
        public Integer getUSRORDER() {
            return usrorder;
        }

        /**
         * Sets the value of the usrorder property.
         * 
         */
        public void setUSRORDER(Integer value) {
            this.usrorder = value;
        }

        /**
         * Gets the value of the usrsex property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSRSEX() {
            return usrsex;
        }

        /**
         * Sets the value of the usrsex property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSRSEX(String value) {
            this.usrsex = value;
        }

        /**
         * Gets the value of the usrmobile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSRMOBILE() {
            return usrmobile;
        }

        /**
         * Sets the value of the usrmobile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSRMOBILE(String value) {
            this.usrmobile = value;
        }

        /**
         * Gets the value of the usrofficeemail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSROFFICEEMAIL() {
            return usrofficeemail;
        }

        /**
         * Sets the value of the usrofficeemail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSROFFICEEMAIL(String value) {
            this.usrofficeemail = value;
        }

        /**
         * Gets the value of the usrstatus property.
         * 
         */
        public Integer getUSRSTATUS() {
            return usrstatus;
        }

        /**
         * Sets the value of the usrstatus property.
         * 
         */
        public void setUSRSTATUS(Integer value) {
            this.usrstatus = value;
        }

        /**
         * Gets the value of the usrpwdmd5 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSRPWDMD5() {
            return usrpwdmd5;
        }

        /**
         * Sets the value of the usrpwdmd5 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSRPWDMD5(String value) {
            this.usrpwdmd5 = value;
        }

        /**
         * Gets the value of the usrplatformid property.
         * 
         */
        public Integer getUSRPLATFORMID() {
            return usrplatformid;
        }

        /**
         * Sets the value of the usrplatformid property.
         * 
         */
        public void setUSRPLATFORMID(Integer value) {
            this.usrplatformid = value;
        }

    }

}
