//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.11 at 05:15:35 下午 CST 
//


package com.bwzk.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Field" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="ColName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="DisName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Attachments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Attachment" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="fileid" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                           &lt;attribute name="filesize" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="filename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="pzm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ftpdir" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "docInfo",
    "attachments"
})
@XmlRootElement(name = "Result")
public class MLXmlResult {

    @XmlElement(name = "DocInfo", required = true)
    protected MLXmlResult.DocInfo docInfo;
    @XmlElement(name = "Attachments", required = true)
    protected MLXmlResult.Attachments attachments;

    /**
     * Gets the value of the docInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MLXmlResult.DocInfo }
     *     
     */
    public MLXmlResult.DocInfo getDocInfo() {
        return docInfo;
    }

    /**
     * Sets the value of the docInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLXmlResult.DocInfo }
     *     
     */
    public void setDocInfo(MLXmlResult.DocInfo value) {
        this.docInfo = value;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * @return
     *     possible object is
     *     {@link MLXmlResult.Attachments }
     *     
     */
    public MLXmlResult.Attachments getAttachments() {
        return attachments;
    }

    /**
     * Sets the value of the attachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLXmlResult.Attachments }
     *     
     */
    public void setAttachments(MLXmlResult.Attachments value) {
        this.attachments = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Attachment" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="fileid" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                 &lt;attribute name="filesize" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="filename" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="pzm" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ftpdir" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attachment"
    })
    public static class Attachments {

        @XmlElement(name = "Attachment")
        protected List<MLXmlResult.Attachments.Attachment> attachment;

        /**
         * Gets the value of the attachment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attachment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttachment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MLXmlResult.Attachments.Attachment }
         * 
         * 
         */
        public List<MLXmlResult.Attachments.Attachment> getAttachment() {
            if (attachment == null) {
                attachment = new ArrayList<MLXmlResult.Attachments.Attachment>();
            }
            return this.attachment;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="fileid" type="{http://www.w3.org/2001/XMLSchema}short" />
         *       &lt;attribute name="filesize" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="filename" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="pzm" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ftpdir" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Attachment {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected String type;
            @XmlAttribute
            protected Short fileid;
            @XmlAttribute
            protected Integer filesize;
            @XmlAttribute
            protected String filename;
            @XmlAttribute
            protected String pzm;
            @XmlAttribute
            protected String ftpdir;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the fileid property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getFileid() {
                return fileid;
            }

            /**
             * Sets the value of the fileid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setFileid(Short value) {
                this.fileid = value;
            }

            /**
             * Gets the value of the filesize property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getFilesize() {
                return filesize;
            }

            /**
             * Sets the value of the filesize property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setFilesize(Integer value) {
                this.filesize = value;
            }

            /**
             * Gets the value of the filename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilename() {
                return filename;
            }

            /**
             * Sets the value of the filename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilename(String value) {
                this.filename = value;
            }

            /**
             * Gets the value of the pzm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPzm() {
                return pzm;
            }

            /**
             * Sets the value of the pzm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPzm(String value) {
                this.pzm = value;
            }

            /**
             * Gets the value of the ftpdir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFtpdir() {
                return ftpdir;
            }

            /**
             * Sets the value of the ftpdir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFtpdir(String value) {
                this.ftpdir = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Field" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="ColName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="DisName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "field"
    })
    public static class DocInfo {

        @XmlElement(name = "Field")
        protected List<MLXmlResult.DocInfo.Field> field;

        /**
         * Gets the value of the field property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the field property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MLXmlResult.DocInfo.Field }
         * 
         * 
         */
        public List<MLXmlResult.DocInfo.Field> getField() {
            if (field == null) {
                field = new ArrayList<MLXmlResult.DocInfo.Field>();
            }
            return this.field;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="ColName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="DisName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Field {

        	@XmlAttribute(name = "Value")
            protected String value;
            @XmlAttribute(name = "ColName")
            protected String colName;
            @XmlAttribute(name = "DisName")
            protected String disName;
            @XmlAttribute
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the colName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColName() {
                return colName;
            }

            /**
             * Sets the value of the colName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColName(String value) {
                this.colName = value;
            }

            /**
             * Gets the value of the disName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisName() {
                return disName;
            }

            /**
             * Sets the value of the disName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDisName(String value) {
                this.disName = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }

}
