
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataSvc", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://121.8.124.109:8888/WebService/LK6SyncService/MrMMSSvc/DataSvc.asmx?wsdl")
public class DataSvc
    extends Service
{

    private final static URL DATASVC_WSDL_LOCATION;
    private final static WebServiceException DATASVC_EXCEPTION;
    private final static QName DATASVC_QNAME = new QName("http://tempuri.org/", "DataSvc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://121.8.124.109:8888/WebService/LK6SyncService/MrMMSSvc/DataSvc.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATASVC_WSDL_LOCATION = url;
        DATASVC_EXCEPTION = e;
    }

    public DataSvc() {
        super(__getWsdlLocation(), DATASVC_QNAME);
    }

    public DataSvc(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATASVC_QNAME, features);
    }

    public DataSvc(URL wsdlLocation) {
        super(wsdlLocation, DATASVC_QNAME);
    }

    public DataSvc(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATASVC_QNAME, features);
    }

    public DataSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataSvc(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataSvcSoap
     */
    @WebEndpoint(name = "DataSvcSoap")
    public DataSvcSoap getDataSvcSoap() {
        return super.getPort(new QName("http://tempuri.org/", "DataSvcSoap"), DataSvcSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataSvcSoap
     */
    @WebEndpoint(name = "DataSvcSoap")
    public DataSvcSoap getDataSvcSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "DataSvcSoap"), DataSvcSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATASVC_EXCEPTION!= null) {
            throw DATASVC_EXCEPTION;
        }
        return DATASVC_WSDL_LOCATION;
    }

}
