
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ImMessageServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    IMObjectFactory.class
})
public interface ImMessageServiceSoap {


    /**
     * ����ЭͬӦ����Ϣ
     * 
     * @param strFromApp
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param strAppTitle
     * @param strUrl
     * @param nReserveDays
     * @param strCustomInfo
     * @param nSenderUserID
     * @param strFromUserName
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessage_std", action = "http://tempuri.org/SendPopupMessage_std")
    @WebResult(name = "SendPopupMessage_stdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessage_std", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageStd")
    @ResponseWrapper(localName = "SendPopupMessage_stdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageStdResponse")
    public String sendPopupMessageStd(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ����ЭͬӦ����Ϣ
     * 
     * @param strFromApp
     * @param sReceiverPlatUserIds
     * @param nOnlineOnly
     * @param strUrl
     * @param strAppTitle
     * @param nSenderUserID
     * @param strCustomInfo
     * @param strFromUserName
     * @param strSubAppcode
     * @param nReserveDays
     * @param strDetailTitle
     * @param nSenderPlatID
     * @param strAppCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessage_stdEx", action = "http://tempuri.org/SendPopupMessage_stdEx")
    @WebResult(name = "SendPopupMessage_stdExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessage_stdEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageStdEx")
    @ResponseWrapper(localName = "SendPopupMessage_stdExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageStdExResponse")
    public String sendPopupMessageStdEx(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo,
        @WebParam(name = "strSubAppcode", targetNamespace = "http://tempuri.org/")
        String strSubAppcode,
        @WebParam(name = "strDetailTitle", targetNamespace = "http://tempuri.org/")
        String strDetailTitle);

    /**
     * ����ЭͬӦ����Ϣ
     * 
     * @param strFromApp
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param strAppTitle
     * @param strUrl
     * @param nReserveDays
     * @param strCustomInfo
     * @param nSenderUserID
     * @param strFromUserName
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessage", action = "http://tempuri.org/SendPopupMessage")
    @WebResult(name = "SendPopupMessageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessage")
    @ResponseWrapper(localName = "SendPopupMessageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageResponse")
    public String sendPopupMessage(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ����ЭͬӦ����Ϣ
     * 
     * @param strFromApp
     * @param sReceiverPlatUserIds
     * @param nOnlineOnly
     * @param strUrl
     * @param strAppTitle
     * @param nSenderUserID
     * @param strCustomInfo
     * @param strFromUserName
     * @param strSubAppcode
     * @param nReserveDays
     * @param strDetailTitle
     * @param nSenderPlatID
     * @param strAppCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageEx", action = "http://tempuri.org/SendPopupMessageEx")
    @WebResult(name = "SendPopupMessageExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageEx")
    @ResponseWrapper(localName = "SendPopupMessageExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageExResponse")
    public String sendPopupMessageEx(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo,
        @WebParam(name = "strSubAppcode", targetNamespace = "http://tempuri.org/")
        String strSubAppcode,
        @WebParam(name = "strDetailTitle", targetNamespace = "http://tempuri.org/")
        String strDetailTitle);

    /**
     * ����ЭͬӦ����ϢCode
     * 
     * @param strFromApp
     * @param nSenderUserCode
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param strAppTitle
     * @param strUrl
     * @param nReserveDays
     * @param strCustomInfo
     * @param strFromUserName
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByUserCode_std", action = "http://tempuri.org/SendPopupMessageByUserCode_std")
    @WebResult(name = "SendPopupMessageByUserCode_stdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByUserCode_std", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeStd")
    @ResponseWrapper(localName = "SendPopupMessageByUserCode_stdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeStdResponse")
    public String sendPopupMessageByUserCodeStd(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ����ЭͬӦ����ϢCode
     * 
     * @param strFromApp
     * @param sReceiverPlatUserIds
     * @param nOnlineOnly
     * @param strUrl
     * @param strAppTitle
     * @param strCustomInfo
     * @param strFromUserName
     * @param nSenderUserCode
     * @param strSubAppcode
     * @param nReserveDays
     * @param strDetailTitle
     * @param nSenderPlatID
     * @param strAppCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByUserCode_stdEx", action = "http://tempuri.org/SendPopupMessageByUserCode_stdEx")
    @WebResult(name = "SendPopupMessageByUserCode_stdExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByUserCode_stdEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeStdEx")
    @ResponseWrapper(localName = "SendPopupMessageByUserCode_stdExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeStdExResponse")
    public String sendPopupMessageByUserCodeStdEx(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo,
        @WebParam(name = "strSubAppcode", targetNamespace = "http://tempuri.org/")
        String strSubAppcode,
        @WebParam(name = "strDetailTitle", targetNamespace = "http://tempuri.org/")
        String strDetailTitle);

    /**
     * ����ЭͬӦ����ϢCode
     * 
     * @param strFromApp
     * @param nSenderUserCode
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param strAppTitle
     * @param strUrl
     * @param nReserveDays
     * @param strCustomInfo
     * @param strFromUserName
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByUserCode", action = "http://tempuri.org/SendPopupMessageByUserCode")
    @WebResult(name = "SendPopupMessageByUserCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByUserCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCode")
    @ResponseWrapper(localName = "SendPopupMessageByUserCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeResponse")
    public String sendPopupMessageByUserCode(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ����ЭͬӦ����ϢCode
     * 
     * @param strFromApp
     * @param sReceiverPlatUserIds
     * @param nOnlineOnly
     * @param strUrl
     * @param strAppTitle
     * @param strCustomInfo
     * @param strFromUserName
     * @param nSenderUserCode
     * @param strSubAppcode
     * @param nReserveDays
     * @param strDetailTitle
     * @param nSenderPlatID
     * @param strAppCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByUserCodeEx", action = "http://tempuri.org/SendPopupMessageByUserCodeEx")
    @WebResult(name = "SendPopupMessageByUserCodeExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByUserCodeEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeEx")
    @ResponseWrapper(localName = "SendPopupMessageByUserCodeExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeExResponse")
    public String sendPopupMessageByUserCodeEx(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo,
        @WebParam(name = "strSubAppcode", targetNamespace = "http://tempuri.org/")
        String strSubAppcode,
        @WebParam(name = "strDetailTitle", targetNamespace = "http://tempuri.org/")
        String strDetailTitle);

    /**
     * ������ͨ�ⲿӦ����Ϣ
     * 
     * @param strFromApp
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param nReserveDays
     * @param strCustomInfo
     * @param nSenderUserID
     * @param strFromUserName
     * @param strAppCode
     * @param strContent
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCommonMessage_std", action = "http://tempuri.org/SendCommonMessage_std")
    @WebResult(name = "SendCommonMessage_stdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCommonMessage_std", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageStd")
    @ResponseWrapper(localName = "SendCommonMessage_stdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageStdResponse")
    public String sendCommonMessageStd(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strContent", targetNamespace = "http://tempuri.org/")
        String strContent,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ������ͨ�ⲿӦ����Ϣ
     * 
     * @param strFromApp
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param nReserveDays
     * @param strCustomInfo
     * @param nSenderUserID
     * @param strFromUserName
     * @param strAppCode
     * @param strContent
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCommonMessage", action = "http://tempuri.org/SendCommonMessage")
    @WebResult(name = "SendCommonMessageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCommonMessage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessage")
    @ResponseWrapper(localName = "SendCommonMessageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageResponse")
    public String sendCommonMessage(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strContent", targetNamespace = "http://tempuri.org/")
        String strContent,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ������ͨ�ⲿӦ����Ϣ
     * 
     * @param strFromApp
     * @param nSenderUserCode
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param nReserveDays
     * @param strCustomInfo
     * @param strFromUserName
     * @param strAppCode
     * @param strContent
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCommonMessageByUserCode_std", action = "http://tempuri.org/SendCommonMessageByUserCode_std")
    @WebResult(name = "SendCommonMessageByUserCode_stdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCommonMessageByUserCode_std", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByUserCodeStd")
    @ResponseWrapper(localName = "SendCommonMessageByUserCode_stdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByUserCodeStdResponse")
    public String sendCommonMessageByUserCodeStd(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strContent", targetNamespace = "http://tempuri.org/")
        String strContent,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ������ͨ�ⲿӦ����Ϣ
     * 
     * @param strFromApp
     * @param nSenderUserCode
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param nReserveDays
     * @param strCustomInfo
     * @param strFromUserName
     * @param strAppCode
     * @param strContent
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCommonMessageByUserCode", action = "http://tempuri.org/SendCommonMessageByUserCode")
    @WebResult(name = "SendCommonMessageByUserCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCommonMessageByUserCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByUserCode")
    @ResponseWrapper(localName = "SendCommonMessageByUserCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByUserCodeResponse")
    public String sendCommonMessageByUserCode(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strContent", targetNamespace = "http://tempuri.org/")
        String strContent,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * @param sReceiverPlatUserIds
     * @param strCustomInfo
     * @param nSenderUserID
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCountChangeMessage", action = "http://tempuri.org/SendCountChangeMessage")
    @WebResult(name = "SendCountChangeMessageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCountChangeMessage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCountChangeMessage")
    @ResponseWrapper(localName = "SendCountChangeMessageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCountChangeMessageResponse")
    public String sendCountChangeMessage(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * �����������Ϣ
     * 
     * @param sReceiverPlatUserIds
     * @param strCustomInfo
     * @param nSenderUserID
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCountChangeMessage_std", action = "http://tempuri.org/SendCountChangeMessage_std")
    @WebResult(name = "SendCountChangeMessage_stdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCountChangeMessage_std", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCountChangeMessageStd")
    @ResponseWrapper(localName = "SendCountChangeMessage_stdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCountChangeMessageStdResponse")
    public String sendCountChangeMessageStd(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * �����������Ϣ
     * 
     * @param nSenderUserCode
     * @param sReceiverPlatUserIds
     * @param strCustomInfo
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCountChangeMessageByCode", action = "http://tempuri.org/SendCountChangeMessageByCode")
    @WebResult(name = "SendCountChangeMessageByCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCountChangeMessageByCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCountChangeMessageByCode")
    @ResponseWrapper(localName = "SendCountChangeMessageByCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCountChangeMessageByCodeResponse")
    public String sendCountChangeMessageByCode(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * �����������Ϣ
     * 
     * @param nSenderUserCode
     * @param sReceiverPlatUserIds
     * @param strCustomInfo
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCountChangeMessageByCode_std", action = "http://tempuri.org/SendCountChangeMessageByCode_std")
    @WebResult(name = "SendCountChangeMessageByCode_stdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCountChangeMessageByCode_std", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCountChangeMessageByCodeStd")
    @ResponseWrapper(localName = "SendCountChangeMessageByCode_stdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCountChangeMessageByCodeStdResponse")
    public String sendCountChangeMessageByCodeStd(
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ����ЭͬӦ����Ϣ
     * 
     * @param strFromApp
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param strAppTitle
     * @param strUrl
     * @param nReserveDays
     * @param sProcStr
     * @param strCustomInfo
     * @param nSenderUserID
     * @param strFromUserName
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByProcStr_std", action = "http://tempuri.org/SendPopupMessageByProcStr_std")
    @WebResult(name = "SendPopupMessageByProcStr_stdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByProcStr_std", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByProcStrStd")
    @ResponseWrapper(localName = "SendPopupMessageByProcStr_stdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByProcStrStdResponse")
    public String sendPopupMessageByProcStrStd(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ����ЭͬӦ����Ϣ
     * 
     * @param strFromApp
     * @param sReceiverPlatUserIds
     * @param nOnlineOnly
     * @param strUrl
     * @param strAppTitle
     * @param nSenderUserID
     * @param strCustomInfo
     * @param strFromUserName
     * @param strSubAppcode
     * @param nReserveDays
     * @param sProcStr
     * @param strDetailTitle
     * @param nSenderPlatID
     * @param strAppCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByProcStr_stdEx", action = "http://tempuri.org/SendPopupMessageByProcStr_stdEx")
    @WebResult(name = "SendPopupMessageByProcStr_stdExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByProcStr_stdEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByProcStrStdEx")
    @ResponseWrapper(localName = "SendPopupMessageByProcStr_stdExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByProcStrStdExResponse")
    public String sendPopupMessageByProcStrStdEx(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo,
        @WebParam(name = "strSubAppcode", targetNamespace = "http://tempuri.org/")
        String strSubAppcode,
        @WebParam(name = "strDetailTitle", targetNamespace = "http://tempuri.org/")
        String strDetailTitle);

    /**
     * ����ЭͬӦ����Ϣ
     * 
     * @param strFromApp
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param strAppTitle
     * @param strUrl
     * @param nReserveDays
     * @param sProcStr
     * @param strCustomInfo
     * @param nSenderUserID
     * @param strFromUserName
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByProcStr", action = "http://tempuri.org/SendPopupMessageByProcStr")
    @WebResult(name = "SendPopupMessageByProcStrResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByProcStr", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByProcStr")
    @ResponseWrapper(localName = "SendPopupMessageByProcStrResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByProcStrResponse")
    public String sendPopupMessageByProcStr(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ����ЭͬӦ����Ϣ
     * 
     * @param strFromApp
     * @param sReceiverPlatUserIds
     * @param nOnlineOnly
     * @param strUrl
     * @param strAppTitle
     * @param nSenderUserID
     * @param strCustomInfo
     * @param strFromUserName
     * @param strSubAppcode
     * @param nReserveDays
     * @param sProcStr
     * @param strDetailTitle
     * @param nSenderPlatID
     * @param strAppCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByProcStrEx", action = "http://tempuri.org/SendPopupMessageByProcStrEx")
    @WebResult(name = "SendPopupMessageByProcStrExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByProcStrEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByProcStrEx")
    @ResponseWrapper(localName = "SendPopupMessageByProcStrExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByProcStrExResponse")
    public String sendPopupMessageByProcStrEx(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo,
        @WebParam(name = "strSubAppcode", targetNamespace = "http://tempuri.org/")
        String strSubAppcode,
        @WebParam(name = "strDetailTitle", targetNamespace = "http://tempuri.org/")
        String strDetailTitle);

    /**
     * ����ЭͬӦ����ϢCode
     * 
     * @param strFromApp
     * @param nSenderUserCode
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param strAppTitle
     * @param strUrl
     * @param nReserveDays
     * @param sProcStr
     * @param strCustomInfo
     * @param strFromUserName
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByUserCodeProcStr_std", action = "http://tempuri.org/SendPopupMessageByUserCodeProcStr_std")
    @WebResult(name = "SendPopupMessageByUserCodeProcStr_stdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByUserCodeProcStr_std", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeProcStrStd")
    @ResponseWrapper(localName = "SendPopupMessageByUserCodeProcStr_stdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeProcStrStdResponse")
    public String sendPopupMessageByUserCodeProcStrStd(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ����ЭͬӦ����ϢCode
     * 
     * @param strFromApp
     * @param sReceiverPlatUserIds
     * @param nOnlineOnly
     * @param strUrl
     * @param strAppTitle
     * @param strCustomInfo
     * @param strFromUserName
     * @param nSenderUserCode
     * @param strSubAppcode
     * @param nReserveDays
     * @param sProcStr
     * @param strDetailTitle
     * @param nSenderPlatID
     * @param strAppCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByUserCodeProcStr_stdEx", action = "http://tempuri.org/SendPopupMessageByUserCodeProcStr_stdEx")
    @WebResult(name = "SendPopupMessageByUserCodeProcStr_stdExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByUserCodeProcStr_stdEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeProcStrStdEx")
    @ResponseWrapper(localName = "SendPopupMessageByUserCodeProcStr_stdExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeProcStrStdExResponse")
    public String sendPopupMessageByUserCodeProcStrStdEx(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo,
        @WebParam(name = "strSubAppcode", targetNamespace = "http://tempuri.org/")
        String strSubAppcode,
        @WebParam(name = "strDetailTitle", targetNamespace = "http://tempuri.org/")
        String strDetailTitle);

    /**
     * ����ЭͬӦ����ϢCode
     * 
     * @param strFromApp
     * @param nSenderUserCode
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param strAppTitle
     * @param strUrl
     * @param nReserveDays
     * @param sProcStr
     * @param strCustomInfo
     * @param strFromUserName
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByUserCodeProcStr", action = "http://tempuri.org/SendPopupMessageByUserCodeProcStr")
    @WebResult(name = "SendPopupMessageByUserCodeProcStrResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByUserCodeProcStr", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeProcStr")
    @ResponseWrapper(localName = "SendPopupMessageByUserCodeProcStrResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeProcStrResponse")
    public String sendPopupMessageByUserCodeProcStr(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ����ЭͬӦ����ϢCode
     * 
     * @param strFromApp
     * @param sReceiverPlatUserIds
     * @param nOnlineOnly
     * @param strUrl
     * @param strAppTitle
     * @param strCustomInfo
     * @param strFromUserName
     * @param nSenderUserCode
     * @param strSubAppcode
     * @param nReserveDays
     * @param sProcStr
     * @param strDetailTitle
     * @param nSenderPlatID
     * @param strAppCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPopupMessageByUserCodeProcStrEx", action = "http://tempuri.org/SendPopupMessageByUserCodeProcStrEx")
    @WebResult(name = "SendPopupMessageByUserCodeProcStrExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendPopupMessageByUserCodeProcStrEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeProcStrEx")
    @ResponseWrapper(localName = "SendPopupMessageByUserCodeProcStrExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPopupMessageByUserCodeProcStrExResponse")
    public String sendPopupMessageByUserCodeProcStrEx(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strUrl", targetNamespace = "http://tempuri.org/")
        String strUrl,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strAppTitle", targetNamespace = "http://tempuri.org/")
        String strAppTitle,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo,
        @WebParam(name = "strSubAppcode", targetNamespace = "http://tempuri.org/")
        String strSubAppcode,
        @WebParam(name = "strDetailTitle", targetNamespace = "http://tempuri.org/")
        String strDetailTitle);

    /**
     * ������ͨ�ⲿӦ����Ϣ
     * 
     * @param strFromApp
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param nReserveDays
     * @param sProcStr
     * @param strCustomInfo
     * @param nSenderUserID
     * @param strFromUserName
     * @param strAppCode
     * @param strContent
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCommonMessageByProcStr_std", action = "http://tempuri.org/SendCommonMessageByProcStr_std")
    @WebResult(name = "SendCommonMessageByProcStr_stdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCommonMessageByProcStr_std", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByProcStrStd")
    @ResponseWrapper(localName = "SendCommonMessageByProcStr_stdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByProcStrStdResponse")
    public String sendCommonMessageByProcStrStd(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strContent", targetNamespace = "http://tempuri.org/")
        String strContent,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ������ͨ�ⲿӦ����Ϣ
     * 
     * @param strFromApp
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param nReserveDays
     * @param sProcStr
     * @param strCustomInfo
     * @param nSenderUserID
     * @param strFromUserName
     * @param strAppCode
     * @param strContent
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCommonMessageByProcStr", action = "http://tempuri.org/SendCommonMessageByProcStr")
    @WebResult(name = "SendCommonMessageByProcStrResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCommonMessageByProcStr", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByProcStr")
    @ResponseWrapper(localName = "SendCommonMessageByProcStrResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByProcStrResponse")
    public String sendCommonMessageByProcStr(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strContent", targetNamespace = "http://tempuri.org/")
        String strContent,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ������ͨ�ⲿӦ����Ϣ
     * 
     * @param strFromApp
     * @param nSenderUserCode
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param nReserveDays
     * @param sProcStr
     * @param strCustomInfo
     * @param strFromUserName
     * @param strAppCode
     * @param strContent
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCommonMessageByUserCodeProcStr_std", action = "http://tempuri.org/SendCommonMessageByUserCodeProcStr_std")
    @WebResult(name = "SendCommonMessageByUserCodeProcStr_stdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCommonMessageByUserCodeProcStr_std", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByUserCodeProcStrStd")
    @ResponseWrapper(localName = "SendCommonMessageByUserCodeProcStr_stdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByUserCodeProcStrStdResponse")
    public String sendCommonMessageByUserCodeProcStrStd(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strContent", targetNamespace = "http://tempuri.org/")
        String strContent,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * ������ͨ�ⲿӦ����Ϣ
     * 
     * @param strFromApp
     * @param nSenderUserCode
     * @param nOnlineOnly
     * @param sReceiverPlatUserIds
     * @param nReserveDays
     * @param sProcStr
     * @param strCustomInfo
     * @param strFromUserName
     * @param strAppCode
     * @param strContent
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCommonMessageByUserCodeProcStr", action = "http://tempuri.org/SendCommonMessageByUserCodeProcStr")
    @WebResult(name = "SendCommonMessageByUserCodeProcStrResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCommonMessageByUserCodeProcStr", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByUserCodeProcStr")
    @ResponseWrapper(localName = "SendCommonMessageByUserCodeProcStrResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommonMessageByUserCodeProcStrResponse")
    public String sendCommonMessageByUserCodeProcStr(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserCode", targetNamespace = "http://tempuri.org/")
        String nSenderUserCode,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strContent", targetNamespace = "http://tempuri.org/")
        String strContent,
        @WebParam(name = "nOnlineOnly", targetNamespace = "http://tempuri.org/")
        short nOnlineOnly,
        @WebParam(name = "nReserveDays", targetNamespace = "http://tempuri.org/")
        short nReserveDays,
        @WebParam(name = "strFromApp", targetNamespace = "http://tempuri.org/")
        String strFromApp,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strFromUserName", targetNamespace = "http://tempuri.org/")
        String strFromUserName,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * �����������Ϣ
     * 
     * @param sReceiverPlatUserIds
     * @param sProcStr
     * @param strCustomInfo
     * @param nSenderUserID
     * @param strAppCode
     * @param nSenderPlatID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCountChangeMessageByProcStr", action = "http://tempuri.org/SendCountChangeMessageByProcStr")
    @WebResult(name = "SendCountChangeMessageByProcStrResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCountChangeMessageByProcStr", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCountChangeMessageByProcStr")
    @ResponseWrapper(localName = "SendCountChangeMessageByProcStrResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCountChangeMessageByProcStrResponse")
    public String sendCountChangeMessageByProcStr(
        @WebParam(name = "sProcStr", targetNamespace = "http://tempuri.org/")
        String sProcStr,
        @WebParam(name = "nSenderPlatID", targetNamespace = "http://tempuri.org/")
        long nSenderPlatID,
        @WebParam(name = "nSenderUserID", targetNamespace = "http://tempuri.org/")
        long nSenderUserID,
        @WebParam(name = "sReceiverPlatUserIds", targetNamespace = "http://tempuri.org/")
        String sReceiverPlatUserIds,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode,
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo);

    /**
     * �����������Ϣ
     * 
     * @param strCustomInfo
     * @param strAppCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DBMsgCancel", action = "http://tempuri.org/DBMsgCancel")
    @WebResult(name = "DBMsgCancelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DBMsgCancel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DBMsgCancel")
    @ResponseWrapper(localName = "DBMsgCancelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DBMsgCancelResponse")
    public String dbMsgCancel(
        @WebParam(name = "strCustomInfo", targetNamespace = "http://tempuri.org/")
        String strCustomInfo,
        @WebParam(name = "strAppCode", targetNamespace = "http://tempuri.org/")
        String strAppCode);

}
