
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MrBaseService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://121.8.124.109:8888/WebService/LK6SyncService/MrBaseService/MrBaseService.asmx?wsdl")
public class MrBaseService
    extends Service
{

    private final static URL MRBASESERVICE_WSDL_LOCATION;
    private final static WebServiceException MRBASESERVICE_EXCEPTION;
    private final static QName MRBASESERVICE_QNAME = new QName("http://tempuri.org/", "MrBaseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://121.8.124.109:8888/WebService/LK6SyncService/MrBaseService/MrBaseService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MRBASESERVICE_WSDL_LOCATION = url;
        MRBASESERVICE_EXCEPTION = e;
    }

    public MrBaseService() {
        super(__getWsdlLocation(), MRBASESERVICE_QNAME);
    }

    public MrBaseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MRBASESERVICE_QNAME, features);
    }

    public MrBaseService(URL wsdlLocation) {
        super(wsdlLocation, MRBASESERVICE_QNAME);
    }

    public MrBaseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MRBASESERVICE_QNAME, features);
    }

    public MrBaseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MrBaseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MrBaseServiceSoap
     */
    @WebEndpoint(name = "MrBaseServiceSoap")
    public MrBaseServiceSoap getMrBaseServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "MrBaseServiceSoap"), MrBaseServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MrBaseServiceSoap
     */
    @WebEndpoint(name = "MrBaseServiceSoap")
    public MrBaseServiceSoap getMrBaseServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MrBaseServiceSoap"), MrBaseServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MRBASESERVICE_EXCEPTION!= null) {
            throw MRBASESERVICE_EXCEPTION;
        }
        return MRBASESERVICE_WSDL_LOCATION;
    }

}
