
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MrBaseService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://211.98.128.170:8888/WebService/LK6SyncService/MrBaseService/MrBaseService.asmx?wsdl")
public class MrBaseService
    extends Service
{

    private final static URL MRBASESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.tempuri.MrBaseService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tempuri.MrBaseService.class.getResource(".");
            url = new URL(baseUrl, "http://211.98.128.170:8888/WebService/LK6SyncService/MrBaseService/MrBaseService.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://211.98.128.170:8888/WebService/LK6SyncService/MrBaseService/MrBaseService.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MRBASESERVICE_WSDL_LOCATION = url;
    }

    public MrBaseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MrBaseService() {
        super(MRBASESERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "MrBaseService"));
    }

    /**
     * 
     * @return
     *     returns MrBaseServiceSoap
     */
    @WebEndpoint(name = "MrBaseServiceSoap")
    public MrBaseServiceSoap getMrBaseServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "MrBaseServiceSoap"), MrBaseServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MrBaseServiceSoap
     */
    @WebEndpoint(name = "MrBaseServiceSoap")
    public MrBaseServiceSoap getMrBaseServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MrBaseServiceSoap"), MrBaseServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns MrBaseServiceSoap
     */
    @WebEndpoint(name = "MrBaseServiceSoap12")
    public MrBaseServiceSoap getMrBaseServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "MrBaseServiceSoap12"), MrBaseServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MrBaseServiceSoap
     */
    @WebEndpoint(name = "MrBaseServiceSoap12")
    public MrBaseServiceSoap getMrBaseServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MrBaseServiceSoap12"), MrBaseServiceSoap.class, features);
    }

}
